name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # diario
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Usuario
          user: GerardoGM14
          template: classic
          base: header, activity, community, repositories

          # Tema
          config_timezone: America/Lima
          config_display: large
          config_padding: 0

          # Calendario isométrico (LO QUE TE GUSTÓ)
          plugin_calendar: yes
          plugin_calendar_layout: isometric
          plugin_calendar_limit: 365

          # Estadísticas del calendario
          plugin_calendar_details: yes

          # Lenguajes (opcional, útil)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
