name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Usuario
          user: GerardoGM14

          # Archivo de salida (CLAVE)
          filename: metrics.svg

          # Commit automÃ¡tico
          committer_branch: main
          committer_message: "chore: update github metrics"

          # Base
          template: classic
          base: header, activity, community, repositories

          # Config general
          config_timezone: America/Lima
          config_display: large
          config_padding: 0

          # ðŸ“† Isometric calendar (OPCIÃ“N B)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Lenguajes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage

          # OptimizaciÃ³n
          optimize: svg
